### ISSUE TITLE
17 - User CRM Login

### ISSUE THREAD

**Issue by romafederico** [scotch-io/mean-machine-code#44] opened 2016-09-23 19:43 UTC
Hi there

I bought the book and moving forward on it. I'm stuck in the login form, since authService.js returns data.data.success ... instead of data.success. When I try to check the property to login the user or show an error message, I can't do it exactly the way the book describes it.

What can I be doing wrong? See files mainCtrl.js and authService.js

mainCtrl.js

```
angular.module('mainCtrl', [])

.controller('mainController', function($rootScope, $location, Auth) {

    var vm = this;

    vm.loggedIn = Auth.isLoggedIn();

    $rootScope.$on('$routeChangeStart', function() {
        vm.loggedIn = Auth.isLoggedIn();
        Auth.getUser()
            .then(function(data) {
                vm.user = data;
            });
    });

    vm.doLogin = function() {
        vm.processing = true;
        vm.error = '';

        Auth.login(vm.loginData.username, vm.loginData.password)
            .then(function(data) {
                vm.processing = false;
                if (data.success)
                    $location.path('/users');
                else
                    vm.error = data.message;
            });
    };

    vm.doLogout = function() {
        Auth.logout();
        vm.user = {};
        $location.path('/login');
    };
});

```

authService.js

`angular.module('authService', [])

.factory('Auth', function($http, $q, AuthToken) {
    var authFactory = {};

```
authFactory.login = function(username, password) {
    return $http.post('/api/authenticate', {
        username: username,
        password: password
    })
        .then(function(data) {
            console.log("fede", data.data.token);
            AuthToken.setToken(data.token);
            return data;
        });
};

authFactory.logout = function() {
    Auth.setToken();
};

authFactory.isLoggedIn = function() {
    if (AuthToken.getToken())
        return true;
    else
        return false;
};

authFactory.getUser = function() {
    if (AuthToken.getToken())
        return $http.get('/api/me', { cache: true });
    else
        return $q.reject({ message: 'User has no token.' });
};

return authFactory;
```

})

.factory('AuthToken', function($window) {
    var authTokenFactory = {};

```
authTokenFactory.getToken = function() {
    return $window.localStorage.getItem('token');
};

authTokenFactory.setToken = function(token) {
    if(token)
        $window.localStorage.setItem('token', token);
    else
        $window.localStorage.removeItem('token');
};

return authTokenFactory;
```

})

.factory('AuthInterceptor', function($q, AuthToken) {
    var interceptorFactory = {};

```
interceptorFactory.request = function(config) {
    var token = AuthToken.getToken();
    if(token)
        config.headers['x-access-token'] = token;

    return config;
};

interceptorFactory.responseError = function(response) {
    if (response.status == 403) {
        AuthToken.setToken();
        $location.path('/login');
    }
    return $q.reject(response);
};

return interceptorFactory;
```

});`

**Comment by themodernturing** [comment] 2016-10-09 08:06
I am stuck at the same point. Have you found any solutions?

**Comment by themodernturing** [comment] 2016-10-09 10:09
I figured it out. The problem is with Promises in mongoose new version. So if you use mongoose version ~3.8.19, and then use .success instead of .then in your controllers, it will work fine. I am copying my package.js here.

{
  "name": "node-api",
  "main": "server.js",
  "dependencies": {
    "bcrypt-nodejs": "0.0.3",
    "body-parser": "~1.9.3",
    "express": "~4.10.3",
    "jsonwebtoken": "^1.2.0",
    "mongoose": "~3.8.19",
    "morgan": "~1.5.0"
  }
}

Here is the live version on heroku:

https://user-crm-420.herokuapp.com/

**Comment by boxoft** [comment] 2016-11-14 13:50
This issue is caused by the fact that the $http...success() method have been changed to the $http...then() method, while the "data" parameter hasn't been changed accordingly.

**authService.js**

```
    // log a user in
    authFactory.login = function(username, password) {

        // return the promise object and its data
        return $http.post('/api/authenticate', {
            username: username,
            password: password
        })
            .then(function(data) {
                AuthToken.setToken(data.token);
                return data;
            });
    };
```

Let's compare the 3 versions of the official documents of "$http":
https://code.angularjs.org/1.3.20/docs/api/ng/service/$http
https://code.angularjs.org/1.4.12/docs/api/ng/service/$http
https://code.angularjs.org/1.5.8/docs/api/ng/service/$http

```
// Simple GET request example :
$http.get('/someUrl').
  success(function(data, status, headers, config) {
    // this callback will be called asynchronously
    // when the response is available
  }).
  error(function(data, status, headers, config) {
    // called asynchronously if an error occurs
    // or server returns response with an error status.
  });
```

```
// Simple GET request example:
$http({
  method: 'GET',
  url: '/someUrl'
}).then(function successCallback(response) {
    // this callback will be called asynchronously
    // when the response is available
  }, function errorCallback(response) {
    // called asynchronously if an error occurs
    // or server returns response with an error status.
  });
```

The "response" parameter in the $http....then() method is different from the "data" parameter in the $http....success() method. The source code should be fixed in this way.

```
        // log a user in
        authFactory.login = function (username, password) {

            // return the promise object and its data
            return $http.post('/api/authenticate', {
                username: username,
                password: password
            })
                .then(function (response) {
                    data = response.data;
                    AuthToken.setToken(data.token);
                    return data;
                });
        };
```

The **mainCtrl.js** file should be modified in the same way as well.

You may want to download the zip file from https://app.box.com/s/05qdnk96i6h2084em6koo626pud62hos and try it. Please modify the config.js accordingly.

**Closed as completed** 2016-12-01 20:06 UTC
